### PR TITLE
Update testing.cpp

### PR DESCRIPTION
**Pull request by Luigifan**
Fixing grammar because I can :D

PS: I know I have write access but I don't want to write directly in case I bork something. I know you can revert, but I'd still rather be cautious

Will this break translations or is this fine before translations exist?

### CODE REVIEW

**Comment by Wohlstand** [comment]
Don't worry, I created this message first time and I did no translations refresh, so, now is safe ;-)
Also, be careful with missed spaces before quotes:
```C++
...feature."
"Currently,...
```
Will result
```c++
...feature.Currently,...
```

**Comment by Luigifan** [comment]
Ooo, I see. Are you not able to hardcode a line break into these so you don't have to worry so much about it?

**Comment by Wohlstand** [comment]
I made no linebreaks in line to let break this string by message box. Message boxes on different platforms are can hold different number of characters, so, let message box break string as that better.
This is not a line break:
```c++
"meow "
"test"
```
it's a thing allows you to break long strings in code, but compiler unites them into united line.

**Comment by Luigifan** [comment]
I literally just ran it lol and I see what you mean. For whatever reason, I thought you meant line breaks by those :D but yes all is good.

In C#, in order for that to be valid, they have to be united with `+`
```csharp
Console.WriteLine("Hello " +
    "world");
```

**Comment by Luigifan** [comment]
Anyway, speaking of QMessageBoxes, that segways me into something I'd like to do at some point but need to test more on other platforms first.

In Mac OS X, 99% of the dialog boxes that occur (the 1% being dialogs that don't have a parent window shown) occur as sheets (or modal). They fly down from the parent window's title bar. It looks nice and is clear as to what window owns this message box. It's a small thing that makes OS X users feel a little bit more at home. If you want, I could try going through and just setting this one line of code to enable this:
`msgBoxInstance.setWindowModality(Qt::WindowModal);`
Qt 5 makes this super easy.

And this will take the message boxes from doing this:

screen shot 2016-03-22 at 8 18 53 am

To doing this:

screen shot 2016-03-22 at 8 18 15 am

Now, because I don't know how this will react on windows/*nix (I remember in Qt 4, this would cause all kinds of weird ownership issues and whatnot and it was a mess. More than likely fixed in Qt 5), I would more than likely add an `ifdef` for `Q_OS_MACX` so this doesn't screw up other platforms.

Thoughts? :)

**Comment by KevinW1998** [comment]
mac-ish people should have mac-ish stuff... So I think it would be fine

**Comment by Wohlstand** [comment]
anyway a way with:
```C
printf("meow "
"test");
```
is a compile-time, and it is not a concoctation, juts a wrapping string in a code. For runtime concoctation is a strcat thing.
Anyway, in C++ with std::string possible same as in C#:
```C++
std::string t = "meow";
t = t+"test";
std::cout << "meow" << "test";
```

P.S. That message box on Windows with "modal" flag:
msg

**Comment by Luigifan** [comment]
Awesome! When I get a chance, I'll be looking through existing Dialogs and adding in that modality. Also have to test dynamic PGE on 10.7.5 too.

**Comment by Wohlstand** [comment]
Are you built it on that clang which presented with 10.7.5?

**Comment by Luigifan** [comment]
Yeah I just want dynamic to test. I haven't tested yet

**Comment by Luigifan** [comment]
yes

**Pull request merged**
