### PR TITLE
Work on multi-form NPC's, lots of proofreading

### PR DESCRIPTION
**Pull request by jpmac26**

### CODE REVIEW

**Comment by Wohlstand** [comment]
You need to swap LUA-controller to keep working state

**Comment by jpmac26** [comment]
Ah, ok, I look forward to that. Also, is it ok if I continue to use the Container and Contents-ID properties for koopa and parakoopas, or should I do something else?

**Comment by Wohlstand** [comment]
Be sure than if NPC is a container that means user can include any NPC into it. Parakoopa->Koopa->sheel I would to set via LUA-code, but some API needed to be proxied. Tomorrow I will continue my works, but today i'm tired

**Comment by jpmac26** [comment]
But if we use container for Koopas, that would allow users to customize what koopa turn into just like other enemies without having to know LUA. However, I will let you decide, and since you are tired I will leave you alone ;)

**Comment by Wohlstand** [comment]
about LUA I meant than catch onKill/onHarm events and transform NPC if it was stomped. But if you would to allow users reconfig that NPC via ini-file or even via NPC.txt, I would to implement support of custom INI/NPC.TXT parameters which are vizible in the lua code (or there are will have default value if there are not redefined via ini-file/npc.txt)

**Comment by KevinW1998** [comment]
I just want to mentioned that every npc is a lua npc (I call it "lua master class"). This is required for transforming a non-lua npc to a lua npc or a non-lua npc to a lua npc. For non-lua npc, the "lua master class" does not redirect events to the "lua controller".

**Pull request merged**
