### PR TITLE
Command line argument syntax changes

### PR DESCRIPTION
**Pull request by jpmac26**
Changed the "walk subdirectories" argument to be "D" instead of "W" because lots of programs use "D", so it will be a bit more familiar. Also, the program now accepts '/' as well as '-' before the single-letter arguments because Windows programs usually use "slash arguments" instead of the "dash arguments" that Linux and OS X use. Finally, I made the program also accept lowercase arguments, so it's ok if you forget to press Shift when entering every argument ;)

### CODE REVIEW

**Comment by Wohlstand** [comment]
You would rename -W with -D, but keep -W as synonic to keep compatibility with old scripts

**Comment by jpmac26** [comment]
Ok, now both the new and old letter arguments work! Also, I tested the build again, it all compiles and runs!

**Comment by Wohlstand** [comment]
Also, isntead of:

```C++
if(useWindowsArgStyle)
{
...
} else {
...
}
```

you would use
```C++
#ifdef _WIN32
....
#else
....
#endif
```
because built application will don't contain actually dead code which made for another platform. It's not a Java where you should make variables to detect specific platforms, here are macros! :wink:

**Comment by jpmac26** [comment]
Ok, I will change that too!

**Comment by jpmac26** [comment]
Ok, all done!

**Comment by Wohlstand** [comment]
:+1:

**Pull request merged**
